### ISSUE TITLE
Traceback on Copy ARs

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#325]
## Steps to reproduce

Select one or more ARs from the listing table and click the "Copy to new" Button

## Current behavior

ARs are created, but a Traceback occurs in the background

## Expected behavior

ARs are created w/o Tracebacks

## Screenshot (optional)

Traceback:

```
Traceback (most recent call last):
  File "/Users/rbartl/develop/ridingbytes/liscon/liscon.lims/eggs/Products.Archetypes-1.9.17-py2.7.egg/Products/Archetypes/BaseObject.py", line 144, in initializeArchetype
    self.setDefaults()
  File "/Users/rbartl/develop/ridingbytes/liscon/liscon.lims/eggs/Products.Archetypes-1.9.17-py2.7.egg/Products/Archetypes/BaseObject.py", line 420, in setDefaults
    self.Schema().setDefaults(self)
  File "/Users/rbartl/develop/ridingbytes/liscon/liscon.lims/src/bika.lims/bika/lims/monkey/Schema.py", line 72, in setDefaults
    mapply(mutator, *args, **kw)
  File "/Users/rbartl/develop/ridingbytes/liscon/liscon.lims/eggs/Products.Archetypes-1.9.17-py2.7.egg/Products/Archetypes/utils.py", line 111, in mapply
    return method(*args, **kw)
  File "/Users/rbartl/develop/ridingbytes/liscon/liscon.lims/src/bika.lims/bika/lims/__init__.py", line 205, in wrapper
    return func(*args, **kwargs)
TypeError: setRequestID() got an unexpected keyword argument ‚mimetype‘
```

**Comment by Nihadness** [comment]
@ramonski , I followed those functions and found out that it also happens during creation of ARs. Actually it would happen with all _deprecated_ `set` methods of any field. Because `set` functions are called with some `kwargs` here on _setDefaults_ :

https://github.com/senaite/bika.lims/blob/senaite-integration/bika/lims/monkey/Schema.py#L72 

Then since  `set` function is _deprecated_ , before calling that manually added function, we leave some warnings and then call that method **with all `args` and `kwargs`**. See:

https://github.com/senaite/bika.lims/blob/senaite-integration/bika/lims/__init__.py#L205 

At that point, since our overridden `set` method doesn't expect any parameter but _new value_, it leaves that error for us.
I think the easiest way to solve that would be, adding `kwargs` to `set` methods if they are deprecated, although they are not used inside the method.
