### ISSUE TITLE
Asynchronous field updates on AR view fail

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#413]
## Steps to reproduce

- Create a new AR and view it
- Update the values of the header table

## Current behavior

Error message appears and the field value is not updated

## Expected behavior

Field is updated with the inserted value

**Comment by ramonski** [comment]
This probably only happens when the sample type contains a blank:

```
Traceback (most recent call last):
  File "plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/decorators.py", line 24, in decorator
    return f(*args, **kwargs)
  File "plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py", line 60, in to_json
    return self.dispatch()
  File "plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py", line 54, in dispatch
    return router(self.context, self.request, path)
  File "plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/router.py", line 138, in __call__
    return self.view_functions[endpoint](context, request, **values)
  File "bika.lims/bika/lims/jsonapi/update.py", line 123, in update
    obj = context.restrictedTraverse(site_path + obj_path)
  File "Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 317, in restrictedTraverse
    return self.unrestrictedTraverse(path, default, restricted=True)
  File "Zope2-2.13.26-py2.7.egg/OFS/Traversable.py", line 285, in unrestrictedTraverse
    raise e
AttributeError: wm%20KSS-0005-R01  <------------ note the %20 which is an escaped space!
```

**Comment by ramonski** [comment]
Ok, I've just seen that the prefix field of sample types disallow spaces and actually validates it correctly. The prefixes I have in the system seem therefore old and need to be changed accordingly.
