### ISSUE TITLE
ShowPrices doctest is failing

### ISSUE THREAD

**Issue by xispa** [senaite/bika.lims#463]
## Steps to reproduce

```
bin/test -t ShowPrices
```

## Current behavior

The test passes in my instance (with latest `master`),

```
$ bin/test -t ShowPrices

Running bika.lims.testing.BikaLIMSLayer:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.212 seconds.
  Set up plone.app.testing.layers.PloneFixture in 13.703 seconds.
  Set up bika.lims.testing.BikaLIMSLayer in 15.807 seconds.
  Set up bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
  Running:
    1/1 (100.0%)/xispa/zinstance/src/bika.lims/bika/lims
                
  Ran 1 tests with 0 failures and 0 errors in 32.571 seconds.

Tearing down left over layers:
  Tear down bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
  Tear down bika.lims.testing.BikaLIMSLayer in 0.005 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.051 seconds.
  Tear down plone.testing.z2.Startup in 0.005 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
```

but not in Travis (i.e. https://travis-ci.org/senaite/bika.lims/builds/314680821?utm_source=github_status&utm_medium=notification for PR https://github.com/senaite/bika.lims/pull/460):

```
Failure in test /home/travis/build/senaite/bika.lims/bika/lims/tests/doctests/ShowPrices.rst
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for ShowPrices.rst
  File "/home/travis/build/senaite/bika.lims/bika/lims/tests/doctests/ShowPrices.rst", line 0
----------------------------------------------------------------------
File "/home/travis/build/senaite/bika.lims/bika/lims/tests/doctests/ShowPrices.rst", line 169, in ShowPrices.rst
Failed example:
    True if "409" not in browser.contents else "Accreditation listing should not have Price column, but it is visible."
Differences (ndiff with -expected +actual):
    - True
    + 'Accreditation listing should not have Price column, but it is visible.'
----------------------------------------------------------------------
File "/home/travis/build/senaite/bika.lims/bika/lims/tests/doctests/ShowPrices.rst", line 185, in ShowPrices.rst
Failed example:
    True if "409" not in browser.contents else "Profile Analyses should NOT be showing Price."
Differences (ndiff with -expected +actual):
    - True
    + 'Profile Analyses should NOT be showing Price.'
----------------------------------------------------------------------
File "/home/travis/build/senaite/bika.lims/bika/lims/tests/doctests/ShowPrices.rst", line 201, in ShowPrices.rst
Failed example:
    True if "409"  not in browser.contents else "AR Templates should NOT be showing Price."
Differences (ndiff with -expected +actual):
    - True
    + 'AR Templates should NOT be showing Price.'
```

## Expected behavior

`ShowPrices.rst` test passes both in dev environment and in Travis.

**Comment by xispa** [comment]
Ummmm... puzzled. It works for https://github.com/senaite/bika.lims/pull/462 , that is a branch from `master` as well as  https://github.com/senaite/bika.lims/pull/460 ..... and `ShowPrices.rst` hasn't been touched in any of the two....

```
$ bin/test -m bika.lims
Running bika.lims.testing.BikaLIMSLayer:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.297 seconds.
  Set up plone.app.testing.layers.PloneFixture in 11.451 seconds.
  Set up bika.lims.testing.BikaLIMSLayer in 19.320 seconds.
  Set up bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
                  
  Ran 42 tests with 0 failures and 0 errors in 44 minutes 53.954 seconds.
Tearing down left over layers:
  Tear down bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
  Tear down bika.lims.testing.BikaLIMSLayer in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.051 seconds.
  Tear down plone.testing.z2.Startup in 0.004 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.009 seconds.

The command "bin/test -m bika.lims" exited with 0.
```

**Comment by ramonski** [comment]
Not sure, but I think it started to fail with my latest changes in the `getSampleTypeTitle` method?

**Comment by xispa** [comment]
I removed the `deprecated` decorator, but was not failing because of that. In the last two PRs opened this morning (both branched from latest `master`), all tests pass: https://github.com/senaite/bika.lims/pull/464 https://github.com/senaite/bika.lims/pull/462 . So, once merged, I think we can close this issue.

**Comment by xispa** [comment]
Random behavior in Travis. Always works in my local instance, but somehow, sometimes works in Travis and sometimes, not. Puzzling
